### ISSUE TITLE
Pod version 2.2.9 does not appear to be a valid

### ISSUE THREAD

**Issue by enmiller** [bazaarvoice/bv-ios-sdk#12]
Updating our code base to v2.2.8 works as expected with the BVSDK Pod being installed.  When upgrading to v2.2.9, Cocoapods rejects the update stating that it cannot satisfy the requirements of BVSDK = 2.2.9

I went the Cocoapods website and searched for bv-ios-sdk and it still shows the latest version of the Pod is 2.2.8

Any ideas?

**Comment by JasonJasonJason** [comment]
Yeah - I am facing some cocoapod verification errors with 2.2.9, but am looking into fixing those now!

**Comment by JasonJasonJason** [comment]
2.2.9 is up on cocoapods. Thanks @enmiller!
