### ISSUE TITLE
Sorting reviews doesn't work

### ISSUE THREAD

**Issue by filippovdev** [bazaarvoice/bv-ios-sdk#17]
Im trying to sort reviews, here is my code:
```
let reviewsRequest = BVReviewsRequest(productId: productID, limit: limit, offset: curentPage)
        reviewsRequest.addSort(.lastReviewTime, order: .descending)
        reviewsRequest.loadReviews(reviewsRequest, completion: { (response) in
            onCompletition(response.results)
        }) { (error) in
            onCompletition(nil)
        }
```
But in most cases I receive error:
2017-01-27 08:18:35.407 MyApp[46232:3111027] <bazaarvoice>: ERROR_PARAM_INVALID_SORT_ATTRIBUTE: Invalid REVIEWS sort field name: LastReviewTime
And the same for most BVSortOptionProducts !

I cant find out how to sort by date.

If api doesn't support some sort options why you didn't add this to any documentation ? I need to spend tons of time just to find out which sort option is working !

I found that addSort method waiting BVSortOptionProducts parameter and it is doesn't work but I see in the sdk another enum BVSortOptionReviews, maybe this method must take this type of sort option ?

**Comment by austimkelly** [comment]
`I found that addSort method waiting BVSortOptionProducts parameter and it is doesn't work but I see in the sdk another enum BVSortOptionReviews, maybe this method must take this type of sort option ?`

You are correct on that. Appears we put the wrong filter enums in that API. I'm double checking and updating unit tests, but should be able to send out an update pretty quick. Thanks for reporting this, and sorry for the inconvenience.

--Tim

**Comment by filippovdev** [comment]
Thank you @austimkelly for quick support. Waiting SDK update (hope it will be soon).

**Comment by austimkelly** [comment]
@filippovdev Yes, I can get out an update soon!

**Comment by austimkelly** [comment]
Hi @filippovdev 6.2.1 has the fix. I'll close this issue out, but let us know if you need any other assistance.

https://github.com/bazaarvoice/bv-ios-sdk/releases/tag/6.2.1

--Tim
