### ISSUE TITLE
apiversion

### ISSUE THREAD

**Issue by a7ex** [bazaarvoice/bv-ios-sdk#18]
The value for the key "apiversion" in each request seems to be hardcoded to 5.4 in the latest version of the SDK.
I can see that in the code of the SDK.
Nonetheless  what the backend reports is apiversion: 5.3 (which is deprecated and will not work properly as of April 2017). I was provided by the following screenshot from the backend for requests, which were definitely done using version 6.20 of the iOS SDK.

![apicallsbv](https://cloud.githubusercontent.com/assets/1708146/22434253/9ebf8036-e71b-11e6-8d57-a2b25b6e27be.jpg)

In the screenshot the requests, which come from the app, have a value of 5.3 for apiversion.

Where does the difference come from and what can I do about it?

**Comment by austimkelly** [comment]
@a7ex Can you tell me which passkey you are using (via private mail). Send email to mobilecoreteam@bazaarvoice.com   I don't see any problem with the API request, but we need to check the key's configuration to know more.

**Comment by austimkelly** [comment]
This one appears to be an issue from the web hosted display. SDK is recording API-leve fine. Closing out.
