### ISSUE TITLE
BVProductDisplayPageRequest, where is the filter ?? 

### ISSUE THREAD

**Issue by filippovdev** [bazaarvoice/bv-ios-sdk#20]
Hello, Im trying to receive statistics with first reviews, everything is ok, but, additionally I need to filter out **isRatingsOnly**  reviews. I can do this with BVReviewsRequest (.add method) but I cant do this in BVProductDisplayPageRequest, its annoying, I need to call API 2 times, first to receive statistics and second time to receive first 10 reviews without rating only, it can be fixed ?

**Comment by austimkelly** [comment]
Hi @filippovdev You can't filter on includes so the `BVProductDisplayPageRequest` won't work like you want. The other option would be to add includes on `BVReviewsRequest` so you can get the product stats and still be able to filter like you want. For example, we'd need to update the SDK to add on `Include=Products&Stats=Reviews`,

Let me know your thoughts on that.

**Comment by austimkelly** [comment]
Sorry, I missed a way to filter. We can make this work by adding the filter on the included reviews. The statistics stay the same, but you get rid of the reviews you don't want, for example:

```
 let request = BVProductDisplayPageRequest(productId: "test1")
            .include(.reviews, limit: 10)
            .include(.questions, limit: 5)
            // only include reviews where isRatingsOnly is false
            .addIncludedReviewsFilter(.isRatingsOnly, filterOperator: .equalTo, value: "false")
            // only include questions where isFeatured is not equal to true
            .addIncludedQuestionsFilter(.isFeatured, filterOperator: .notEqualTo, value: "true")
            .includeStatistics(.reviews)
```

**Comment by austimkelly** [comment]
PR: https://github.com/bazaarvoice/bv-ios-sdk-dev/pull/241

Notes:

* I don't think any docs are needed, unless we want to update the examples. But I did add some light headerdoc to the BVProductDispalyPageRequest.h file.

* There is not BVAnswerFilter support, so I did not add anything WRT filtering answers.

**Comment by austimkelly** [comment]
Fixed in https://github.com/bazaarvoice/bv-ios-sdk/releases/tag/6.4.1

**Comment by filippovdev** [comment]
@austimkelly Thank you for quick support !
