### ISSUE TITLE
Adding "extra" fields to BVReviewSubmission

### ISSUE THREAD

**Issue by filippovdev** [bazaarvoice/bv-ios-sdk#21]
Hi dear friends, Im trying to submit review but without luck, server return me that missing some required fields in request, this fields:
- "rating_design"
- "rating_ease"
- "rating_expectations"
- "rating_value"
Ok, Im trying to send them somehow, I trying: 
`BVReviewSubmission.addAdditionalField`
but without luck, because for example when I add "rating_design" with this method:
`review.addAdditionalField("rating_design", value: "4")`
In request it looks like:
`additional_field_rating_design`
 and of course server again sad that required fields missing.

And another "maybe bug" what I mention, when I choose:
`review.action = .submit //review is BVReviewSubmission object`
in request to bazaarvoice server it still shows in send parameters: 
`action = Preview`
and no matter what I choose submit or preview.

I use SDK 6.4.0

**Comment by austimkelly** [comment]
Hi @filippovdev Here's some sample code that should do what you want:

```
        let reviewSubmission = BVReviewSubmission(reviewTitle: "Review Title",
                                                   reviewText: "Review text...This needs to be long enough to be accepted.",
                                                       rating: 5,
                                                    productId: "test1")
        
        // a working example of posting a review.
        reviewSubmission.action = .submit // Don't actually post, just run in preview mode!
        
        // We need to use the same userId for both the photo post and review content
        let userId = "123abc\(arc4random())"
        
        reviewSubmission.userNickname = userId
        reviewSubmission.userEmail = "foo@bar.com"
        reviewSubmission.userId = userId
        reviewSubmission.isRecommended = true
        reviewSubmission.sendEmailAlertWhenPublished = true
        reviewSubmission.addRatingQuestion("value", value: 5)
        reviewSubmission.addRatingQuestion("design", value: 4)
        reviewSubmission.addRatingQuestion("ease", value: 3)
        reviewSubmission.addRatingQuestion("expectations", value: 2)
        
        if let photo = UIImage(named: "puppy"){
            reviewSubmission.addPhoto(photo, withPhotoCaption: "5 star pup!")
        }
        
        reviewSubmission.submit({ (response) in
            self.showAlertSuccess(message: "Success Submitting Review!")
        }) { (error) in
            self.showAlertError(message: error.description)
        }
```

If you have verbose logging you will see that there is a first call with `action = Preview` which is just a quick validation check to make sure all the fields are OK. Then you will see `action = Submit` once the fields are validated. I think you never saw the `action = Submit` because you had not added the ratings fields correctly for you configuration.

I'll close this one out for now, but let me know if that doesn't work and we can check again.
