### ISSUE TITLE
Can't send pros and cons with BVReviewRequest

### ISSUE THREAD

**Issue by filippovdev** [bazaarvoice/bv-ios-sdk#22]
Hello, I trying to find out how to send pros and cons with BVReviewRequest.

Im looking here:
https://bazaarvoice.github.io/bv-ios-sdk/content_submission.html#reviews
and inside Xcode example, and didn't find how to send this information.

It is one of the most important thing, and it missed in documentation.

To show pros and cons we use:
 BVReview.tagDimensions?["Cons"]
 BVReview.tagDimensions?["Pros"]

But how to post them ?

**Comment by austimkelly** [comment]
Hi @filippovdev - Try this:

`reviewSubmission.addPredefinedTagDimension("Con", tagId: "1", value: "Text input up to 50 chars.")`

That will produce a parameter in the POST:

`"tagid_Con/1" = "Text input up to 50 chars.";`

Let me know how that works and I can update the doccs (agree, very important missing part). 

Also, if you run a submission in preview mode, you can see all the required and optional fields required for submission. This appears in the `formFields` dictionary for all the submission response objects:

https://github.com/bazaarvoice/bv-ios-sdk/blob/d1760f9ec1911f487cbaa4193c5d53f3913b5668/Pod/BVConversations/Submission/BVSubmissionResponse.h#L21

**Comment by filippovdev** [comment]
@austimkelly Hm, for some reason it doesn't work, server return success but I didn't receive them in BVReview.tagDimensions.

**Comment by austimkelly** [comment]
> some reason it doesn't work
@filippovdev Does this mean when running a submission in preview mode you can't see any of the tag dimensions? I can't really tell without knowing you API key used. If you send email to mobilecoreteam@bazaarvoice.com with the API key you are using and a product ID I can get it a check.

It should only take 15 minutes to be able to check your submission after a successful Action=Submit.

**Comment by filippovdev** [comment]
@austimkelly It should but my yesterday posts still doesn't appear, I using staging key and "test1" product ID. Here is the post and response, everything look fine for me:

Will write you email.

**Comment by filippovdev** [comment]
@austimkelly will write email to you. Don't know reason, but from yesterday nothing appear on staging server, I use standard "test1" product ID and post request return success, only voting working for me with same very long delay.

**Comment by austimkelly** [comment]
Closing this out. This is more related to an internal configuration than the SDK itself.
