### ISSUE TITLE
Review request does not have options to add "Include" parameter

### ISSUE THREAD

**Issue by srikanth-vm** [bazaarvoice/bv-ios-sdk#23]
API supports inclusion of associated product along with reviews, but the `BVReviewsRequest` class does not provide a method to add this parameter. 

Does it help if I could send a PR for it ?

**Comment by austimkelly** [comment]
Hi @srikanth-vm I just added that yesterday in fact. It might take a 1-2 weeks before it gets into our release cycle. Looks like this, where you can include the product, and the product will have statistics (or filtered statistics)

`- (nonnull instancetype)addInclude:(BVReviewIncludeType)include;`

Is that timing OK for you?

**Comment by austimkelly** [comment]
Hi @srikanth-vm version 6.5.0 should do what you want:

https://github.com/bazaarvoice/bv-ios-sdk/blob/master/Pod/BVConversations/Display/Requests/BVBaseReviewsRequest.h#L37
