### ISSUE TITLE
BazaarVoice Conversations - isSyndicated Review Flag

### ISSUE THREAD

**Issue by rwbutler** [bazaarvoice/bv-ios-sdk#24]
On fetching review data an isSyndicated flag is returned in the JSON but doesn't appear to be exposed through the BVReview object in the API. Where a review is syndicated, there doesn't appear to be any means to retrieve the source of the syndicated review either (or may be undocumented).

Can this information be surfaced through the API?

**Comment by austimkelly** [comment]
Fixed in 6.5.1
