### ISSUE TITLE
Crash in BVTransactionEvent.m

### ISSUE THREAD

**Issue by springstephen** [bazaarvoice/bv-ios-sdk#26]
## The Problem

Call to BVPixel.trackEvent() sometimes crashes. Looks like the BVTransactionEvent does a nil check for the currency before inserting into the eventDict, but ends up inserting the city instead. If city is nil the app crashes.

## Steps to Reproduce

Track a checkout with no city value.

## Expected Behavior

No crash.

## Environment

* iPhone devices running iOS 12.0 and greater

## Details

**From BVTransactionEvent.m line 99**
  if (self.currency) {
    [eventDict setObject:self.city forKey:@"currency"];
  }

**Stack Trace**
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x2268b7ea0 __exceptionPreprocess
1  libobjc.A.dylib                0x225a89a40 objc_exception_throw
2  CoreFoundation                 0x22682f470 _CFArgv
3  CoreFoundation                 0x2267a2b10 -[__NSDictionaryM setObject:forKey:]
4  ZulilyKit                      0x10537deb4 -[BVTransactionEvent crateBaseEvent:] (BVTransactionEvent.m:99)
5  ZulilyKit                      0x10537d7e0 -[BVTransactionEvent toRaw] (BVTransactionEvent.m:35)
6  ZulilyKit                      0x10537cb8c +[BVPixel trackEvent:] (BVPixel.m:30)

**Comment by chris-pound-bazaarvoice** [comment]
Thanks for reporting this. We've opened an internal ticket to investigate and update the sdk with a fix.

**Comment by chris-pound-bazaarvoice** [comment]
8.0.3 was released with a fix for this issue. 
https://github.com/bazaarvoice/bv-ios-sdk/releases/tag/8.0.3
