### ISSUE TITLE
Display image content only

### ISSUE THREAD

**Issue by rwbutler** [bazaarvoice/bv-ios-sdk#30]
## The Problem

We'd like to be able to filter out video and only display photo content from the feed. Its is possible to do this in `BVCurationsCollectionView` by setting 

```
req.hasPhoto = @YES;
```

However there doesn't appear to be a way to configure the curations view to do this without changing the curations view itself. It would be very helpful to be able to configure this externally to the curations view so that there is no need to modify the class directly.

**Comment by cameron-ollivierre** [comment]
Thank you for your input. We've looked into this, and have opened a ticket to add this functionality. I will update this thread with a commit link once the update is available.

**Comment by rwbutler** [comment]
That's great - thanks for looking into this 👍🏻

**Comment by cameron-ollivierre** [comment]
I know it's been a while, but just wanted to let you know that our latest release includes the enhancement to curations that was previously discussed.
