### ISSUE TITLE
Duplicate review submissions

### ISSUE THREAD

**Issue by imran-muhammad** [bazaarvoice/bv-ios-sdk#31]
Duplicate reviews being submitted and success closure on submitting a review is executing twice (failure closure only executes once). We noticed this issue after updating to SDK version 8+.

Installation: Carthage

Code:

func submitReview(review: HLReview, onSuccess: @escaping () -> Void, onFailure: @escaping (String) -> Void) {

        let reviewSubmission = BVReviewSubmission(reviewTitle: review.title!,
                                                  reviewText: review.text!,
                                                  rating: UInt(truncating: review.rating!),
                                                  productId: review.styleID!)        
        reviewSubmission.action = BVSubmissionAction.submit
        reviewSubmission.userNickname = review.userNickName
        reviewSubmission.userEmail = review.email
        reviewSubmission.sendEmailAlertWhenPublished = true
        reviewSubmission.agreedToTermsAndConditions = true
        reviewSubmission.hostedAuthenticationEmail = review.email
        reviewSubmission.submit({ _ in
            onSuccess()
        }, failure: { (errors) in
            onFailure(errors.description)
        })
    }

**Comment by cameron-ollivierre** [comment]
Thanks for reporting this issue. We've opened an internal ticket to further investigate.

**Comment by domoniquecarter35** [comment]
Has there been any updates on this? I can confirm I also get the issue on SDK 8.0.

**Comment by imran-muhammad** [comment]
> Has there been any updates on this? I can confirm I also get the issue on SDK 8.0.

I have not seen any updates yet.

**Comment by narcisvoicu** [comment]
I've also encountered this issue while using SDK 8.1.0. I found an workaround, there's a property _userId_ and somehow if you set that property, the second call it will point to failure instead of success.

**Comment by abhinavmandloiBV** [comment]
This issue has been resolved in the latest version 8.1.1.
