### ISSUE TITLE
SwiftPM Support

### ISSUE THREAD

**Issue by jsorge** [bazaarvoice/bv-ios-sdk#34]
We are re-evaluating our dependency management system and seriously considering Swift Package Manager. Do you have any plans to support adding your SDK through SwiftPM?

**Comment by abhinavmandloiBV** [comment]
Hi @jsorge,

We have plans to provide Swift Package Manager support but currently, it has not been prioritized.

We will update you whenever we take that up in future.

Thanks

cc: @karanhanda1991

**Comment by abhinavmandloiBV** [comment]
We have released a new version for iOS Swift SDK. Please find the details below:

BVSwift (version - 1.5.0): https://cocoapods.org/pods/BVSwift and https://github.com/bazaarvoice/bv-ios-swift-sdk/releases/tag/1.5.0

Release notes:
- Added support for Swift Package Manager
