### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by srikanth-vm** [bazaarvoice/bv-ios-sdk#36]
Hello,

We are moving away from Carthage and planning to use SPM as the primary dependency manager for our iOS applications.
Do you have any plans of adding support for SPM shortly ?

**Comment by abhinavmandloiBV** [comment]
Hi @srikanth-vm,

we do have the ticket for support for Swift Package Manager in our backlog but we haven't prioritised it yet. So currently, we don't have an ETA as to when that would be picked up by the team and completed.

**Comment by abhinavmandloiBV** [comment]
Hi @srikanth-vm,

We have released a new version for iOS Swift SDK. Please find the details below:

BVSwift (version - 1.5.0): https://cocoapods.org/pods/BVSwift and https://github.com/bazaarvoice/bv-ios-swift-sdk/releases/tag/1.5.0

Release notes:
- Added support for Swift Package Manager
