### ISSUE TITLE
Pod is outdated, importing incorrect files.

### ISSUE THREAD

**Issue by thiagoperes** [bazaarvoice/bv-ios-sdk#6]
The podspec points to version 2.1.5 and imports files contained in CocoapodsIgnore folder (BVDummy class).

**Comment by JasonJasonJason** [comment]
Fixed, at version 2.2.4 now.

**Comment by nickhart** [comment]
It looks to me like the Pod is still out of date.  If It try to include it in a project I get version 2.1.5.  I believe you still need to run "pod trunk push BVSDK.podspec".
