### ISSUE TITLE
v2.1.6 contains local framework search paths warnings for Alex Medearis in the 

### ISSUE THREAD

**Issue by mcgregok** [bazaarvoice/bv-ios-sdk#7]
warning:

warning: (i386) /Users/alex.medearis/Desktop/bv-ios-sdk/Source/BVSDK/build/BVSDK.build/Debug-iphonesimulator/BVSDK.build/Objects-normal/i386/BVNetwork.o unable to open object file
warning: (i386) /Users/alex.medearis/Desktop/bv-ios-sdk/Source/BVSDK/build/BVSDK.build/Debug-iphonesimulator/BVSDK.build/Objects-normal/i386/BVGet.o unable to open object file
warning: (i386) /Users/alex.medearis/Desktop/bv-ios-sdk/Source/BVSDK/build/BVSDK.build/Debug-iphonesimulator/BVSDK.build/Objects-normal/i386/BVPost.o unable to open object file
warning: (i386) /Users/alex.medearis/Desktop/bv-ios-sdk/Source/BVSDK/build/BVSDK.build/Debug-iphonesimulator/BVSDK.build/Objects-normal/i386/BVMediaPost.o unable to open object file
warning: (i386) /Users/alex.medearis/Desktop/bv-ios-sdk/Source/BVSDK/build/BVSDK.build/Debug-iphonesimulator/BVSDK.build/Objects-normal/i386/BVSettings.o unable to open object file
warning: (i386) /Users/alex.medearis/Desktop/bv-ios-sdk/Source/BVSDK/build/BVSDK.build/Debug-iphonesimulator/BVSDK.build/Objects-normal/i386/BVMultipartStream.o unable to open object file

**Comment by JasonJasonJason** [comment]
With new SDK installment methods (CocoaPods or manually as described in the readme) this should no longer be an issue
