### ISSUE TITLE
iOS 8 SDK 64 bit Support

### ISSUE THREAD

**Issue by merkmaloney** [bazaarvoice/bv-ios-sdk#8]
Starting February 1, 2015, new iOS apps uploaded to the App Store must include 64-bit support and be built with the iOS 8 SDK, included in Xcode 6 or later. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code.

BazaarVoice SDK does not support 64-bit.

ld: warning: ignoring file /Volumes/Files/ios/anthro/Pods/Bazaarvoice/BVSDK.framework/BVSDK, missing required architecture x86_64 in file /Volumes/Files/ios/anthro/Pods/Bazaarvoice/BVSDK.framework/BVSDK (3 slices)

**Comment by JasonJasonJason** [comment]
It looked like two ways of including the SDK would cause this issue, even though it was set to build for Standard Architectures. To fix things, I restructured things to align with CocoaPods' suggested structure, and simplified adding the SDK manually.

Should be fixed now! :) @nickhart Could you confirm?

**Comment by nickhart** [comment]
It works if I directly include the BV source files into my project, but the CocoaPod is still out of date.

**Comment by JasonJasonJason** [comment]
@nickhart thanks for checking! Are you by chance using the "Bazaarvoice" pod? If so, please change to the "BVSDK" pod. We had some ownership issues with the Bazaarvoice pod and are trying to resolve that with the Cocoapod group to only have the BVSDK pod.

**Comment by nickhart** [comment]
Yep, that did it!  Sorry for the confusion.  I inherited our Podfile from someone else.

**Comment by nickhart** [comment]
I think you can close this issue.

**Comment by JasonJasonJason** [comment]
Thanks!
